### ISSUE TITLE
CircleCI: fuzz and e2e test failed

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/optimism#112]
cannon-fuzz, op-e2e-fuzz, op-e2e-HTTP-tests, op-e2e-action-tests, op-e2e-fault-proof-tests and the final bedrock-go-tests are [failed](https://app.circleci.com/pipelines/circleci/VJoJbnHRXJiFR13mWFvRfZ/SHyYDZiLFYMtveJSZVFKbw/24/workflows/01ee261b-f023-4a74-84b6-d6c2453b6fbd)

Also need to check the following action status when our credits are available:
 - check-generated-mocks-op-node
 - check-generated-mocks-op-service
 - cannon-go-lint-and-test
 - cannon-build-test-vectors
 - todo-issues
 - shellcheck/check

**Comment by syntrust** [comment]
The fuzz tests are fixed by installing Python on AX101.
The e2e tests disappeared or were renamed after the latest merge with upstream. 

Now all the jobs mentioned in this issue pass, except one test in `op-e2e-HTTP-tests` that is moved to `go-tests`, and is now tracked by https://github.com/ethstorage/optimism/issues/136
